version: '3.4'

services:

  java:
    image: danielcifuentes54/java-metrics
    ports:
      - "8080:8080"
    networks:
      - app-net

  prometheus:
    image: danielcifuentes54/prometheus-java-metrics
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: danielcifuentes54/grafana-java-metrics
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net: