global:
  scrape_interval: 10s
  external_labels:
    monitor: 'local-monitor'

scrape_configs:

  - job_name: 'java'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['java:8080']

  - job_name: 'docker-workers'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9323']