{
 "title": "Java Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"java\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"java\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"java\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Web Service Counter1",
   "type": "singlestat",
   "description": "Sum of total request Web Service 1\n",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dc_total_request_total{name=\"counter1\"})"
    },
    {}
   ]
  },
  {
   "title": "average transaction sleep ms",
   "type": "gauge",
   "description": "/service/sleep",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 3 },
   "targets": [
    {
     "expr": "(http_server_requests_seconds_sum{uri=\"/service/sleep\"} / http_server_requests_seconds_count{uri=\"/service/sleep\"}) * 100"
    }
   ]
  },
  {
   "title": "Web Service Counter2",
   "type": "singlestat",
   "description": "Sum of total request Web Service 2\n",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dc_total_request_total{name=\"counter2\"})"
    },
    {}
   ]
  }
 ]
}